{
 "title": "DistriSchool - Overview",
 "tags": [ "distrischool" ],
 "refresh": "10s",
 "panels": [
  { "title": "Application Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "HTTP Server Requests (count)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by (job,uri) (increase(http_server_requests_seconds_count[5m]))",
     "legendFormat": "{{job}} - {{uri}}"
    }
   ]
  },
  {
   "title": "JVM Memory Used (bytes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    { "expr": "jvm_memory_used_bytes", "legendFormat": "{{area}} - {{job}}" }
   ]
  },
  {
   "title": "Process CPU (seconds)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    { "expr": "process_cpu_seconds_total", "legendFormat": "{{job}}" }
   ]
  }
 ]
}